using System.Collections.Generic;
using TMPro;
using UnityEngine;

public class RaceManager : MonoBehaviour
{
    // SINGLETON STARTS
    private static RaceManager myInstance;
    private void Singleton()
    {
        if (myInstance != null && myInstance != this)
        {
            Destroy(this.gameObject);
            return;
        }
        else
        {
            myInstance = this;
        }
    }
    public static RaceManager Load => myInstance;
    // SINGLETON ENDS

    // INSPECTOR VARIABLES
    [Header("Audio")]
    [NonReorderable]
    [SerializeField] private AudioClip[] myCountDownAudioClips = null;
    [SerializeField] private AudioSource myAudioSource = null;

    [Header("Other Data Needed")]
    [SerializeField] private TextMeshProUGUI theCountDownText = null;
    [SerializeField] private TextMeshProUGUI theUpdateText = null;
    [SerializeField] private TextMeshProUGUI theLapText = null;
    [SerializeField] private TextMeshProUGUI thePositionText = null;
    [SerializeField] private GameObject theFinishUI = null;

    // LOCAL VARIABLES
    private List<GameObject> myRacers;
    private bool myGameStart;
    private bool myRaceOver;
    private bool myResetText;
    private float myStartRaceCountdownSeconds;
    private int myTrackLaps;
    private int myCurrentLap;
    private int myAudioCount;
    private int thePlayerPosition;
    private GameObject thePlayer;

    // GETTERS
    public bool GetRaceOver => myRaceOver;
    public bool GetGameStarted => myGameStart;
    public int GetRacers => myRacers.Count;
    public int GetCurrentLap => myCurrentLap;
    public int GetPlayerPosition => thePlayerPosition;

    // SETTERS
    public void AddRacers(GameObject me) => myRacers.Add(me);
    public void ResetRacers() => myRacers.Clear();
    public int SetPlayerPosition(int position) => thePlayerPosition = position;
    public int SetCurrentLap(int lap) => myCurrentLap = lap;

    private void Awake()
    {
        Singleton();
    }

    private void Start()
    {
        InitializeVariables();
    }

    private void Update()
    {
        myStartRaceCountdownSeconds -= Time.deltaTime;
        RaceCountdown();
        UpdateHUDText();
        UpdateLastLap();
        RaceOver();
    }

    private void InitializeVariables()
    {
        myGameStart = false;
        myRaceOver = false;
        myResetText = false;
        myStartRaceCountdownSeconds = 4;
        myCurrentLap = 0;
        myAudioCount = 0;
        myTrackLaps = LoadingManager.Load.GetCurrentTrackLaps;
        myRacers = LoadingManager.Load.GetTotalVehicles;
        thePlayer = LoadingManager.Load.GetPlayer;
    }

    private void RaceOver()
    {
        if (myCurrentLap > myTrackLaps)
        {
            thePositionText.text = "Position: " + thePlayerPosition + " of " + (LoadingManager.Load.GetTrackPolePositions);
            theLapText.text = "Lap: " + myTrackLaps + " of " + myTrackLaps;
            theUpdateText.text = "  YOU FINISHED  " + thePlayerPosition;
            myRaceOver = true;
            theFinishUI.SetActive(true);
        }
    }

    private void UpdateLastLap()
    {
        if (myCurrentLap == myTrackLaps && !myResetText)
        {
            if (!myAudioSource.isPlaying && myAudioCount == 0)
            {
                myAudioSource.PlayOneShot(myCountDownAudioClips[4]);
                myAudioCount++;
            }
            theUpdateText.text = "LAST LAP!";
            Invoke(nameof(ResetLapText), 2);
        }
    }

    private void UpdateHUDText()
    {
        if (myGameStart && myCurrentLap <= myTrackLaps)
        {
            theLapText.text = "Lap: " + myCurrentLap + " of " + myTrackLaps;
            thePositionText.text = "Position: " + thePlayerPosition + " of " + (LoadingManager.Load.GetTrackPolePositions);
        }
    }

    private void RaceCountdown()
    {
        if (!myGameStart && myStartRaceCountdownSeconds > 1)
        {
            if (Mathf.Floor(myStartRaceCountdownSeconds) == 3)
            {
                if (!myAudioSource.isPlaying && myAudioCount == 0)
                {
                    myAudioSource.PlayOneShot(myCountDownAudioClips[0]);
                    myAudioCount++;
                }
            }
            else if (Mathf.Floor(myStartRaceCountdownSeconds) == 2)
            {
                if (!myAudioSource.isPlaying && myAudioCount == 1)
                {
                    myAudioSource.PlayOneShot(myCountDownAudioClips[1]);
                    myAudioCount++;
                }
            }
            else if (Mathf.Floor(myStartRaceCountdownSeconds) == 1)
            {
                if (!myAudioSource.isPlaying && myAudioCount == 2)
                {
                    myAudioSource.PlayOneShot(myCountDownAudioClips[2]);
                    myAudioCount++;
                }
            }
            theCountDownText.text = Mathf.Floor(myStartRaceCountdownSeconds).ToString();
        }
        else if (myStartRaceCountdownSeconds < 1 && myStartRaceCountdownSeconds >= -1)
        {
            if (!myAudioSource.isPlaying && myAudioCount == 3)
            {
                myAudioSource.PlayOneShot(myCountDownAudioClips[3]);
                myAudioCount = 0;
            }
            theCountDownText.text = "GO";
            myGameStart = true;
        }
        else
        {
            theCountDownText.text = "";
        }
    }

    private void ResetLapText()
    {
        myResetText = true;
        theUpdateText.text = "";
    }

    public void ResetLevel()
    {
        InitializeVariables();
        myRacers.Clear();
        thePositionText.text = "";
        theLapText.text = "";
        theUpdateText.text = "";
    }
}
